Update
KimeraMoses/dav-safaris pull request #1
Opened 2023-07-08 10:45 UTC by ssemugenyi

# Davsafaris changes

## Dashboard

### Manage countries(new)
Added creating, editing, deleting a new country, and fetching all countries
Refetching countries after creating a new country
### Manage categories(new)
Added creating, editing, deleting a new country, and fetching all categories
Refetching category after creating a new category
### Manage tours
Fetching countries and categories dynamically for each tour
Refetching tours after creating a new tour

## Navigation Menu
Added other destinations  dropdown  with a slider 
Responsiveness of the navigation on all devices

## Homepage
Fetching all countries and populating them in the search component
Added a carousel component for all countries created

## Country Single and Category Single Page
Fetched country and category by slug
Added a skeleton to the page before loading content

2023-07-12 06:37 UTC, KimeraMoses commented
![image](https://github.com/KimeraMoses/dav-safaris/assets/55502046/2ed70445-1133-4766-8850-0262a83957e0)

This section still has dummy countries, can you please make them dynamic with countries with most number of tours

2023-07-12 06:41 UTC, KimeraMoses commented
![image](https://github.com/KimeraMoses/dav-safaris/assets/55502046/b50618ae-513d-4f4f-922f-54c5e922b5d3)

Can we eliminate any country with zero countries from the list in the agent dashboard, it doesn't make sense for us to show them a country with no tours

2023-07-12 06:46 UTC, KimeraMoses commented
![image](https://github.com/KimeraMoses/dav-safaris/assets/55502046/24e0128a-74c3-4b69-a31f-0ea40575eede)

Make uganda to be the default of this select by county dropdown since all the countries displayed initially are for Uganda

2023-07-12 07:06 UTC, KimeraMoses requested changes
Please fix these issues and those raised in the issue section and let me know when you have pushed the code

2023-07-12 07:06 UTC, KimeraMoses commented on src/components/DashBoard/ManageCountries/EditCountry.js
> +                    <TextField
Completely remove this section please

2023-07-12 07:06 UTC, KimeraMoses commented on src/components/DashBoard/ManageCountries/delete/DeleteModal.js
> +      // dispatch(fetchAllCountrys());
Remove any redux related code that we have commented out and not using. This includes the slices, actions and any other file or line of code that you are sure that we are not using any more

2023-07-12 07:10 UTC, KimeraMoses commented
![image](https://github.com/KimeraMoses/dav-safaris/assets/55502046/09a23e88-6a37-4ddc-86f9-11900713e010)
Remove this field from this form and from anyother form that you worked on, we don't need it visible at all

2023-07-12 07:12 UTC, KimeraMoses commented
![image](https://github.com/KimeraMoses/dav-safaris/assets/55502046/ebd195e8-59ca-4892-b1e9-9d8010b1c0f6)
These two fields are quite confusing, can you please change the labels to something less confusing. I'm sure admins will be asking what we mean by title and name

2023-07-12 07:18 UTC, KimeraMoses commented
![image](https://github.com/KimeraMoses/dav-safaris/assets/55502046/09307052-0004-41e1-b49a-474c4971081f)
This is how the live Kenya version looks like and below is how the new version looks like, question:

![image](https://github.com/KimeraMoses/dav-safaris/assets/55502046/7b77ad87-6caa-4c03-bcc3-48239c873ae3)

Where are these categories, once deployed, we shall not be viewing these categories if not created, we need to create them for any country that had them ensuring that nothing gets broken in the middle of the process.

2023-07-12 07:19 UTC, ssemugenyi commented on src/components/CountryTours/CountryHeader.js
> +  // let categories = fetchedCategories.categories;
Okay am going to fix them, let me wait for Isaac to first create the popular destinations endpoint

2023-07-12 07:22 UTC, KimeraMoses commented
![image](https://github.com/KimeraMoses/dav-safaris/assets/55502046/c57c7968-9612-4ef4-b527-b6c925e55edc)
The reload button doesn't work for the safari updates and language posts, could you have an idea why this is like this?

2023-07-24 08:54 UTC, merged

2023-07-24 09:09 UTC, KimeraMoses commented
All changes merged to master